# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200511_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
